


Homework 0 - Team 4 Duke Dinosaurs
========================================================

### Implementation

<!--
Use this section to implement the fizzbuzz function.

This should include a short write up describing your appraoch
to implementing the function. Not both code formating / style
and your writeup matter for your overall grade.
-->

The layout of our function is simple. Inside a function that we are
storing inside variable "FizzBuzz", we used the "IF" command within 
the forloop function to solve the problem.
 
Our function's input value is "n". 

Inside our function, the first "IF" Statement tells the function that 
should the input "n" not be a vector (using "!" to symbolize not), the 
function should stop running the function and return an error message 
"Please input ...".
 
The first forloop, we have two "IF" Statements. 
The first tells R that if the element(s) in the input isn't a numeric, it should display an error message requesting the input be nuemeric. 
The second tells R that if the element(s) in the input isn't an integer, it should display an error message requesting the input be of integers. 

In our second forloop, we specify some conditions for the elements, x, inside n.
Our "IF" Statement says that if the element modulo 15 equals 0, the word
"FizzBuzz" will print. 
For the cases where the element modulo 15 doesn't equal 1, if the element 
modulo 3 equals 0, the word "Fizz" will print.
For the cases where the first two conditions aren't met, if the element 
modulo 5 equals 0, the word "Buzz" will print. 
For all the remaining cases, the element will just print itself. 

We then call our function with the command FizzBuzz and let our input n
be the sequence from 1 to 100. 

In conclusion, we first specified the conditions for the function's 
input. We then looped into the sequence we created to determine what 
should appear within that sequence and when it should appear. Lastly, 
we ran the function.
 
```{r} 
FizzBuzz = function(n) {
  if(!is.vector(n)){
    stop("Please input a integer or a vector of integers.")
  } # if n isn't a vector, show this error message #
  for (i in n){
            if (!is.numeric(i)) stop("Please input numerics only")
    # if elements in n aren't numeric, show this error message #
            if (!(i%%1==0)) stop("Please input integers only")
    # if elements in n modulo 1 don't equal 0, show this error message #
  } # for loop that will go through each element in input n #
  for (x in n){
    if (x%%15==0) print("FizzBuzz")
    # in the case where the elemtn in n is divisble by 15 #
    # print 'FizzBuzz' #
    else if (x%%3==0) print("Fizz") 
    # in the case where the element in n is divisble by 3 # 
    # print 'Fizz' #
    else if (x%%5==0) print("Buzz") 
    # in the case where the element in n is divisible by 5 #
    # print 'Buzz' #
    else 
    print(x) # prints out element inside input n #
  } 
  # for loop that will go through each element in n and print out each element #
}

FizzBuzz(n=1:100)
# call the function and let the input be the seqeunce from 1 to 100 #

